server:
  port: 8080

spring:
  application:
    name: AiLowCurrentEngineer
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/lowcurrent
    username: postgres
    password: a785410a
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  thymeleaf:
    cache: false
  sql:
    init:
      mode: never
security:
  jwt:
    secret: cXeLRverb9aiz/7cvXztl9RkSkMVPV4fX/Q1utchsx8hw1VWENf52QE/26bbsEHrQ0DDHzoKf+zYgXEwwrf8Zg==
    ttlMillis: 86400000

planner:
  url: http://localhost:8000

s3:
  endpoint: http://minio:9000
  access-key: admin
  secret-key: a785410a
  bucket-raw: lowcurrent-raw
  bucket-exports: ai-lowcurrent-exports
